platform :ios, '15.1'

use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

target 'ConvayTestSDK' do
  pod 'JitsiMeetSDK', '11.5.1'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end


